version: "3.8"
services:

  sleekforum:
    build:
      context: src
      args:
        dev_env: production
    networks:
      - db
      - webserver
    env_file:
      - ./configs/env/postgres.env
      - ./configs/env/sleekforum.env
    environment:
      - SLEEKFORUM_DB_HOST=postgres
    volumes:
      - ./src:/srv/http/sleekforum

  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgres/data
    networks:
      - db
    env_file:
      - ./configs/env/postgres.env
    expose:
      - 5000
      - 5432
    ports:
      - "5000:5000"
      - "5001:5432"

  nginx:
    build:
      context: nginx
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./src/static:/srv/ftp/sleekforum/static
      - ./src/media:/srv/ftp/sleekforum/media
    ports:
      - "4042:80"

networks:
  db:
  webserver:

volumes:
  pg_data: