# Generated by Django 3.0.6 on 2020-05-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20200517_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageFlag',
        ),
    ]
