# Generated by Django 3.0.6 on 2020-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_delete_messageflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flag',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Active and New')], default=2, verbose_name='flag'),
        ),
    ]
