# Generated by Django 3.0.7 on 2020-06-16 13:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Post content')),
                ('is_hidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='dislikes')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='title')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(), blank=True, null=True, size=None)),
                ('pin', models.IntegerField(choices=[(0, 'Do not pin thread'), (1, 'Pin thread within category'), (2, 'Pin thread globally')], default=0, verbose_name='pin thread')),
                ('prefix', models.IntegerField(choices=[(0, 'Default'), (1, 'Help'), (2, 'Discussion'), (3, 'Info')], default=0, verbose_name='prefix')),
                ('slug', models.SlugField(blank=True, editable=False, verbose_name='slug')),
                ('content', models.TextField(unique_for_date='created', verbose_name='content')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False, verbose_name='lock thread')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='hide thread')),
                ('is_editable', models.BooleanField(default=True, verbose_name='allow edit')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='total likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='total dislikes')),
                ('shares', models.PositiveIntegerField(default=0, verbose_name='total shares')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='ThreadEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=255)),
                ('editor_slug', models.SlugField()),
                ('edits', models.PositiveSmallIntegerField(default=0)),
                ('last_edit_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_views', to='threads.Thread')),
            ],
        ),
    ]
