# Generated by Django 3.0.5 on 2020-04-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='total_likes',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='thread',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='total dislikes'),
        ),
        migrations.AddField(
            model_name='thread',
            name='favorites',
            field=models.PositiveIntegerField(default=0, verbose_name='total favorites'),
        ),
    ]
