# Generated by Django 3.0.4 on 2020-03-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20200330_2258'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='threadview',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_together_thread_user'),
        ),
    ]
