# Generated by Django 3.0.5 on 2020-05-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20200507_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='total dislikes'),
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='total likes'),
        ),
    ]
