# Generated by Django 3.0.8 on 2020-07-02 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0002_auto_20200616_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='starter'),
        ),
    ]
