# Generated by Django 3.0.5 on 2020-04-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20200418_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='views',
        ),
    ]
