# Generated by Django 3.0.2 on 2020-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_thread_is_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='is_editable',
        ),
    ]
