# Generated by Django 3.0.4 on 2020-03-07 13:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('threads', '0003_auto_20200306_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='thread',
            name='type',
        ),
        migrations.AddField(
            model_name='thread',
            name='prefix',
            field=models.CharField(choices=[(0, 'Default'), (1, 'Help'), (2, 'Discussion'), (3, 'Info')], default=0, max_length=2, verbose_name='prefix'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='ThreadType',
        ),
    ]
