# Generated by Django 3.0.7 on 2020-06-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20200609_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='tags',
        ),
    ]
