# Generated by Django 3.0.4 on 2020-03-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20200307_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='prefix',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Help'), (2, 'Discussion'), (3, 'Info')], default=0, verbose_name='prefix'),
        ),
    ]
