# Generated by Django 3.0.2 on 2020-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_remove_thread_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_editable',
            field=models.BooleanField(default=True, verbose_name='allow edit'),
        ),
    ]
