# Generated by Django 3.0.5 on 2020-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20200420_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='shares',
            field=models.PositiveIntegerField(default=0, verbose_name='total shares'),
        ),
        migrations.AddField(
            model_name='thread',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
