# Generated by Django 3.0.4 on 2020-03-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0005_thread_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='pin',
            field=models.IntegerField(choices=[(0, 'Do not pin thread'), (1, 'Pin thread within category'), (2, 'Pin thread globally')], default=0, verbose_name='pin thread'),
        ),
        migrations.CreateModel(
            name='ThreadRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('show_rule', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_by', models.ManyToManyField(related_name='thread_reports', to=settings.AUTH_USER_MODEL)),
                ('rules_broken', models.ManyToManyField(related_name='thread_reports', to='threads.ThreadRule')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_reports', to='threads.Thread')),
            ],
        ),
    ]
