# Generated by Django 3.0.8 on 2020-07-15 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rules', '0002_rule_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_violated', models.IntegerField(choices=[(0, 'Awaiting actions'), (1, 'Accepted violation'), (2, 'Rejected violation')], default=0, verbose_name='accept violation')),
                ('reported_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='reported on')),
                ('penalty', models.IntegerField(choices=[(0, 'No action'), (1, 'Hide object'), (2, 'Ban user'), (3, 'Delete object and Ban User')], default=0, help_text='Proper measure to be taken against violation', verbose_name='penalty')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('rules', models.ManyToManyField(related_name='violations', related_query_name='violations', to='rules.Rule', verbose_name='rules violated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action_value', models.CharField(choices=[('FAV', 'Favorite'), ('LIK', 'Like'), ('DSL', 'Dislike'), ('UVT', 'Up Vote'), ('DVT', 'Down Vote')], max_length=3, verbose_name='Action')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['content_type', 'object_id'], name='index_ct_id'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('user', 'action_value', 'content_type', 'object_id'), name='unique_user_activity'),
        ),
    ]
