# Generated by Django 3.0.7 on 2020-06-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20200608_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='penalties',
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
