# Generated by Django 3.0.4 on 2020-03-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username_slug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_hide_presence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='threads',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'slug'), name='unique_user'),
        ),
    ]
