# Generated by Django 3.0.7 on 2020-06-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_lock',
            field=models.BooleanField(default=True, help_text='Determine whether category should         serve as thread section', verbose_name='lock category'),
        ),
    ]
