version: "3.8"
services:

  sleekforum:
    build:
      context: .
    networks:
      - db
    environment:
      - SLEEKFORUM_DB_HOST=postgres
    restart: unless-stopped
    volumes:
      - .:/srv/http/sleekforum:z
    depends_on:
      - postgres
    ports:
    - "8000:4042"

  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgres/data
    restart: always
    networks:
      - db
    environment:
      - POSTGRES_USER=flyuser
      - POSTGRES_PASSWORD=flyuser
      - POSTGRES_DB=flyforum

networks:
  db:

volumes:
  pg_data: